dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}

networks:
  default: hardhat-local
  live:
    gas_limit: max
    reverting_tx_gas_limit: False

compiler:
  solc:
    version: null
  
autofetch_sources: True